///|
pub const Key_Escape = 0x01000000

///|
pub const Key_Tab = 0x01000001

///|
pub const Key_Backtab = 0x01000002

///|
pub const Key_Backspace = 0x01000003

///|
pub const Key_Return = 0x01000004

///|
pub const Key_Enter = 0x01000005

///|
pub const Key_Insert = 0x01000006

///|
pub const Key_Delete = 0x01000007

///|
pub const Key_Pause = 0x01000008

///|
pub const Key_Print = 0x01000009

///|
pub const Key_SysReq = 0x0100000a

///|
pub const Key_Clear = 0x0100000b

///|
pub const Key_Home = 0x01000010

///|
pub const Key_End = 0x01000011

///|
pub const Key_Left = 0x01000012

///|
pub const Key_Up = 0x01000013

///|
pub const Key_Right = 0x01000014

///|
pub const Key_Down = 0x01000015

///|
pub const Key_PageUp = 0x01000016

///|
pub const Key_PageDown = 0x01000017

///|
pub const Key_Shift = 0x01000020

///|
pub const Key_Control = 0x01000021

///|
pub const Key_Meta = 0x01000022

///|
pub const Key_Alt = 0x01000023

///|
pub const Key_AltGr = 0x01001103

///|
pub const Key_CapsLock = 0x01000024

///|
pub const Key_NumLock = 0x01000025

///|
pub const Key_ScrollLock = 0x01000026

///|
pub const Key_F1 = 0x01000030

///|
pub const Key_F2 = 0x01000031

///|
pub const Key_F3 = 0x01000032

///|
pub const Key_F4 = 0x01000033

///|
pub const Key_F5 = 0x01000034

///|
pub const Key_F6 = 0x01000035

///|
pub const Key_F7 = 0x01000036

///|
pub const Key_F8 = 0x01000037

///|
pub const Key_F9 = 0x01000038

///|
pub const Key_F10 = 0x01000039

///|
pub const Key_F11 = 0x0100003a

///|
pub const Key_F12 = 0x0100003b

///|
pub const Key_F13 = 0x0100003c

///|
pub const Key_F14 = 0x0100003d

///|
pub const Key_F15 = 0x0100003e

///|
pub const Key_F16 = 0x0100003f

///|
pub const Key_F17 = 0x01000040

///|
pub const Key_F18 = 0x01000041

///|
pub const Key_F19 = 0x01000042

///|
pub const Key_F20 = 0x01000043

///|
pub const Key_F21 = 0x01000044

///|
pub const Key_F22 = 0x01000045

///|
pub const Key_F23 = 0x01000046

///|
pub const Key_F24 = 0x01000047

///|
pub const Key_F25 = 0x01000048

///|
pub const Key_F26 = 0x01000049

///|
pub const Key_F27 = 0x0100004a

///|
pub const Key_F28 = 0x0100004b

///|
pub const Key_F29 = 0x0100004c

///|
pub const Key_F30 = 0x0100004d

///|
pub const Key_F31 = 0x0100004e

///|
pub const Key_F32 = 0x0100004f

///|
pub const Key_F33 = 0x01000050

///|
pub const Key_F34 = 0x01000051

///|
pub const Key_F35 = 0x01000052

///|
pub const Key_Super_L = 0x01000053

///|
pub const Key_Super_R = 0x01000054

///|
pub const Key_Menu = 0x01000055

///|
pub const Key_Hyper_L = 0x01000056

///|
pub const Key_Hyper_R = 0x01000057

///|
pub const Key_Help = 0x01000058

///|
pub const Key_Direction_L = 0x01000059

///|
pub const Key_Direction_R = 0x01000060

///|
pub const Key_Space = 0x20

///|
pub const Key_Any : Int = Key_Space

///|
pub const Key_Exclam = 0x21

///|
pub const Key_QuoteDbl = 0x22

///|
pub const Key_NumberSign = 0x23

///|
pub const Key_Dollar = 0x24

///|
pub const Key_Percent = 0x25

///|
pub const Key_Ampersand = 0x26

///|
pub const Key_Apostrophe = 0x27

///|
pub const Key_ParenLeft = 0x28

///|
pub const Key_ParenRight = 0x29

///|
pub const Key_Asterisk = 0x2a

///|
pub const Key_Plus = 0x2b

///|
pub const Key_Comma = 0x2c

///|
pub const Key_Minus = 0x2d

///|
pub const Key_Period = 0x2e

///|
pub const Key_Slash = 0x2f

///|
pub const Key_0 = 0x30

///|
pub const Key_1 = 0x31

///|
pub const Key_2 = 0x32

///|
pub const Key_3 = 0x33

///|
pub const Key_4 = 0x34

///|
pub const Key_5 = 0x35

///|
pub const Key_6 = 0x36

///|
pub const Key_7 = 0x37

///|
pub const Key_8 = 0x38

///|
pub const Key_9 = 0x39

///|
pub const Key_Colon = 0x3a

///|
pub const Key_Semicolon = 0x3b

///|
pub const Key_Less = 0x3c

///|
pub const Key_Equal = 0x3d

///|
pub const Key_Greater = 0x3e

///|
pub const Key_Question = 0x3f

///|
pub const Key_At = 0x40

///|
pub const Key_A = 0x41

///|
pub const Key_B = 0x42

///|
pub const Key_C = 0x43

///|
pub const Key_D = 0x44

///|
pub const Key_E = 0x45

///|
pub const Key_F = 0x46

///|
pub const Key_G = 0x47

///|
pub const Key_H = 0x48

///|
pub const Key_I = 0x49

///|
pub const Key_J = 0x4a

///|
pub const Key_K = 0x4b

///|
pub const Key_L = 0x4c

///|
pub const Key_M = 0x4d

///|
pub const Key_N = 0x4e

///|
pub const Key_O = 0x4f

///|
pub const Key_P = 0x50

///|
pub const Key_Q = 0x51

///|
pub const Key_R = 0x52

///|
pub const Key_S = 0x53

///|
pub const Key_T = 0x54

///|
pub const Key_U = 0x55

///|
pub const Key_V = 0x56

///|
pub const Key_W = 0x57

///|
pub const Key_X = 0x58

///|
pub const Key_Y = 0x59

///|
pub const Key_Z = 0x5a

///|
pub const Key_BracketLeft = 0x5b

///|
pub const Key_Backslash = 0x5c

///|
pub const Key_BracketRight = 0x5d

///|
pub const Key_AsciiCircum = 0x5e

///|
pub const Key_Underscore = 0x5f

///|
pub const Key_QuoteLeft = 0x60

///|
pub const Key_BraceLeft = 0x7b

///|
pub const Key_Bar = 0x7c

///|
pub const Key_BraceRight = 0x7d

///|
pub const Key_AsciiTilde = 0x7e

///|
pub const Key_nobreakspace = 0x0a0

///|
pub const Key_exclamdown = 0x0a1

///|
pub const Key_cent = 0x0a2

///|
pub const Key_sterling = 0x0a3

///|
pub const Key_currency = 0x0a4

///|
pub const Key_yen = 0x0a5

///|
pub const Key_brokenbar = 0x0a6

///|
pub const Key_section = 0x0a7

///|
pub const Key_diaeresis = 0x0a8

///|
pub const Key_copyright = 0x0a9

///|
pub const Key_ordfeminine = 0x0aa

///|
pub const Key_guillemotleft = 0x0ab

///|
pub const Key_notsign = 0x0ac

///|
pub const Key_hyphen = 0x0ad

///|
pub const Key_registered = 0x0ae

///|
pub const Key_macron = 0x0af

///|
pub const Key_degree = 0x0b0

///|
pub const Key_plusminus = 0x0b1

///|
pub const Key_twosuperior = 0x0b2

///|
pub const Key_threesuperior = 0x0b3

///|
pub const Key_acute = 0x0b4

///|
pub const Key_micro = 0x0b5

///|
pub const Key_paragraph = 0x0b6

///|
pub const Key_periodcentered = 0x0b7

///|
pub const Key_cedilla = 0x0b8

///|
pub const Key_onesuperior = 0x0b9

///|
pub const Key_masculine = 0x0ba

///|
pub const Key_guillemotright = 0x0bb

///|
pub const Key_onequarter = 0x0bc

///|
pub const Key_onehalf = 0x0bd

///|
pub const Key_threequarters = 0x0be

///|
pub const Key_questiondown = 0x0bf

///|
pub const Key_Agrave = 0x0c0

///|
pub const Key_Aacute = 0x0c1

///|
pub const Key_Acircumflex = 0x0c2

///|
pub const Key_Atilde = 0x0c3

///|
pub const Key_Adiaeresis = 0x0c4

///|
pub const Key_Aring = 0x0c5

///|
pub const Key_AE = 0x0c6

///|
pub const Key_Ccedilla = 0x0c7

///|
pub const Key_Egrave = 0x0c8

///|
pub const Key_Eacute = 0x0c9

///|
pub const Key_Ecircumflex = 0x0ca

///|
pub const Key_Ediaeresis = 0x0cb

///|
pub const Key_Igrave = 0x0cc

///|
pub const Key_Iacute = 0x0cd

///|
pub const Key_Icircumflex = 0x0ce

///|
pub const Key_Idiaeresis = 0x0cf

///|
pub const Key_ETH = 0x0d0

///|
pub const Key_Ntilde = 0x0d1

///|
pub const Key_Ograve = 0x0d2

///|
pub const Key_Oacute = 0x0d3

///|
pub const Key_Ocircumflex = 0x0d4

///|
pub const Key_Otilde = 0x0d5

///|
pub const Key_Odiaeresis = 0x0d6

///|
pub const Key_multiply = 0x0d7

///|
pub const Key_Ooblique = 0x0d8

///|
pub const Key_Ugrave = 0x0d9

///|
pub const Key_Uacute = 0x0da

///|
pub const Key_Ucircumflex = 0x0db

///|
pub const Key_Udiaeresis = 0x0dc

///|
pub const Key_Yacute = 0x0dd

///|
pub const Key_THORN = 0x0de

///|
pub const Key_ssharp = 0x0df

///|
pub const Key_division = 0x0f7

///|
pub const Key_ydiaeresis = 0x0ff

///|
pub const Key_Multi_key = 0x01001120

///|
pub const Key_Codeinput = 0x01001137

///|
pub const Key_SingleCandidate = 0x0100113c

///|
pub const Key_MultipleCandidate = 0x0100113d

///|
pub const Key_PreviousCandidate = 0x0100113e

///|
pub const Key_Mode_switch = 0x0100117e

///|
pub const Key_Kanji = 0x01001121

///|
pub const Key_Muhenkan = 0x01001122

///|
pub const Key_Henkan = 0x01001123

///|
pub const Key_Romaji = 0x01001124

///|
pub const Key_Hiragana = 0x01001125

///|
pub const Key_Katakana = 0x01001126

///|
pub const Key_Hiragana_Katakana = 0x01001127

///|
pub const Key_Zenkaku = 0x01001128

///|
pub const Key_Hankaku = 0x01001129

///|
pub const Key_Zenkaku_Hankaku = 0x0100112a

///|
pub const Key_Touroku = 0x0100112b

///|
pub const Key_Massyo = 0x0100112c

///|
pub const Key_Kana_Lock = 0x0100112d

///|
pub const Key_Kana_Shift = 0x0100112e

///|
pub const Key_Eisu_Shift = 0x0100112f

///|
pub const Key_Eisu_toggle = 0x01001130

///|
pub const Key_Hangul = 0x01001131

///|
pub const Key_Hangul_Start = 0x01001132

///|
pub const Key_Hangul_End = 0x01001133

///|
pub const Key_Hangul_Hanja = 0x01001134

///|
pub const Key_Hangul_Jamo = 0x01001135

///|
pub const Key_Hangul_Romaja = 0x01001136

///|
pub const Key_Hangul_Jeonja = 0x01001138

///|
pub const Key_Hangul_Banja = 0x01001139

///|
pub const Key_Hangul_PreHanja = 0x0100113a

///|
pub const Key_Hangul_PostHanja = 0x0100113b

///|
pub const Key_Hangul_Special = 0x0100113f

///|
pub const Key_Dead_Grave = 0x01001250

///|
pub const Key_Dead_Acute = 0x01001251

///|
pub const Key_Dead_Circumflex = 0x01001252

///|
pub const Key_Dead_Tilde = 0x01001253

///|
pub const Key_Dead_Macron = 0x01001254

///|
pub const Key_Dead_Breve = 0x01001255

///|
pub const Key_Dead_Abovedot = 0x01001256

///|
pub const Key_Dead_Diaeresis = 0x01001257

///|
pub const Key_Dead_Abovering = 0x01001258

///|
pub const Key_Dead_Doubleacute = 0x01001259

///|
pub const Key_Dead_Caron = 0x0100125a

///|
pub const Key_Dead_Cedilla = 0x0100125b

///|
pub const Key_Dead_Ogonek = 0x0100125c

///|
pub const Key_Dead_Iota = 0x0100125d

///|
pub const Key_Dead_Voiced_Sound = 0x0100125e

///|
pub const Key_Dead_Semivoiced_Sound = 0x0100125f

///|
pub const Key_Dead_Belowdot = 0x01001260

///|
pub const Key_Dead_Hook = 0x01001261

///|
pub const Key_Dead_Horn = 0x01001262

///|
pub const Key_Dead_Stroke = 0x01001263

///|
pub const Key_Dead_Abovecomma = 0x01001264

///|
pub const Key_Dead_Abovereversedcomma = 0x01001265

///|
pub const Key_Dead_Doublegrave = 0x01001266

///|
pub const Key_Dead_Belowring = 0x01001267

///|
pub const Key_Dead_Belowmacron = 0x01001268

///|
pub const Key_Dead_Belowcircumflex = 0x01001269

///|
pub const Key_Dead_Belowtilde = 0x0100126a

///|
pub const Key_Dead_Belowbreve = 0x0100126b

///|
pub const Key_Dead_Belowdiaeresis = 0x0100126c

///|
pub const Key_Dead_Invertedbreve = 0x0100126d

///|
pub const Key_Dead_Belowcomma = 0x0100126e

///|
pub const Key_Dead_Currency = 0x0100126f

///|
pub const Key_Dead_a = 0x01001280

///|
pub const Key_Dead_A = 0x01001281

///|
pub const Key_Dead_e = 0x01001282

///|
pub const Key_Dead_E = 0x01001283

///|
pub const Key_Dead_i = 0x01001284

///|
pub const Key_Dead_I = 0x01001285

///|
pub const Key_Dead_o = 0x01001286

///|
pub const Key_Dead_O = 0x01001287

///|
pub const Key_Dead_u = 0x01001288

///|
pub const Key_Dead_U = 0x01001289

///|
pub const Key_Dead_Small_Schwa = 0x0100128a

///|
pub const Key_Dead_Capital_Schwa = 0x0100128b

///|
pub const Key_Dead_Greek = 0x0100128c

///|
pub const Key_Dead_Lowline = 0x01001290

///|
pub const Key_Dead_Aboveverticalline = 0x01001291

///|
pub const Key_Dead_Belowverticalline = 0x01001292

///|
pub const Key_Dead_Longsolidusoverlay = 0x01001293

///|
pub const Key_Back = 0x01000061

///|
pub const Key_Forward = 0x01000062

///|
pub const Key_Stop = 0x01000063

///|
pub const Key_Refresh = 0x01000064

///|
pub const Key_VolumeDown = 0x01000070

///|
pub const Key_VolumeMute = 0x01000071

///|
pub const Key_VolumeUp = 0x01000072

///|
pub const Key_BassBoost = 0x01000073

///|
pub const Key_BassUp = 0x01000074

///|
pub const Key_BassDown = 0x01000075

///|
pub const Key_TrebleUp = 0x01000076

///|
pub const Key_TrebleDown = 0x01000077

///|
pub const Key_MediaPlay = 0x01000080

///|
pub const Key_MediaStop = 0x01000081

///|
pub const Key_MediaPrevious = 0x01000082

///|
pub const Key_MediaNext = 0x01000083

///|
pub const Key_MediaRecord = 0x01000084

///|
pub const Key_MediaPause = 0x01000085

///|
pub const Key_MediaTogglePlayPause = 0x01000086

///|
pub const Key_HomePage = 0x01000090

///|
pub const Key_Favorites = 0x01000091

///|
pub const Key_Search = 0x01000092

///|
pub const Key_Standby = 0x01000093

///|
pub const Key_OpenUrl = 0x01000094

///|
pub const Key_LaunchMail = 0x010000a0

///|
pub const Key_LaunchMedia = 0x010000a1

///|
pub const Key_Launch0 = 0x010000a2

///|
pub const Key_Launch1 = 0x010000a3

///|
pub const Key_Launch2 = 0x010000a4

///|
pub const Key_Launch3 = 0x010000a5

///|
pub const Key_Launch4 = 0x010000a6

///|
pub const Key_Launch5 = 0x010000a7

///|
pub const Key_Launch6 = 0x010000a8

///|
pub const Key_Launch7 = 0x010000a9

///|
pub const Key_Launch8 = 0x010000aa

///|
pub const Key_Launch9 = 0x010000ab

///|
pub const Key_LaunchA = 0x010000ac

///|
pub const Key_LaunchB = 0x010000ad

///|
pub const Key_LaunchC = 0x010000ae

///|
pub const Key_LaunchD = 0x010000af

///|
pub const Key_LaunchE = 0x010000b0

///|
pub const Key_LaunchF = 0x010000b1

///|
pub const Key_LaunchG = 0x0100010e

///|
pub const Key_LaunchH = 0x0100010f

///|
pub const Key_MonBrightnessUp = 0x010000b2

///|
pub const Key_MonBrightnessDown = 0x010000b3

///|
pub const Key_KeyboardLightOnOff = 0x010000b4

///|
pub const Key_KeyboardBrightnessUp = 0x010000b5

///|
pub const Key_KeyboardBrightnessDown = 0x010000b6

///|
pub const Key_PowerOff = 0x010000b7

///|
pub const Key_WakeUp = 0x010000b8

///|
pub const Key_Eject = 0x010000b9

///|
pub const Key_ScreenSaver = 0x010000ba

///|
pub const Key_WWW = 0x010000bb

///|
pub const Key_Memo = 0x010000bc

///|
pub const Key_LightBulb = 0x010000bd

///|
pub const Key_Shop = 0x010000be

///|
pub const Key_History = 0x010000bf

///|
pub const Key_AddFavorite = 0x010000c0

///|
pub const Key_HotLinks = 0x010000c1

///|
pub const Key_BrightnessAdjust = 0x010000c2

///|
pub const Key_Finance = 0x010000c3

///|
pub const Key_Community = 0x010000c4

///|
pub const Key_AudioRewind = 0x010000c5

///|
pub const Key_BackForward = 0x010000c6

///|
pub const Key_ApplicationLeft = 0x010000c7

///|
pub const Key_ApplicationRight = 0x010000c8

///|
pub const Key_Book = 0x010000c9

///|
pub const Key_CD = 0x010000ca

///|
pub const Key_Calculator = 0x010000cb

///|
pub const Key_ToDoList = 0x010000cc

///|
pub const Key_ClearGrab = 0x010000cd

///|
pub const Key_Close = 0x010000ce

///|
pub const Key_Copy = 0x010000cf

///|
pub const Key_Cut = 0x010000d0

///|
pub const Key_Display = 0x010000d1

///|
pub const Key_DOS = 0x010000d2

///|
pub const Key_Documents = 0x010000d3

///|
pub const Key_Excel = 0x010000d4

///|
pub const Key_Explorer = 0x010000d5

///|
pub const Key_Game = 0x010000d6

///|
pub const Key_Go = 0x010000d7

///|
pub const Key_iTouch = 0x010000d8

///|
pub const Key_LogOff = 0x010000d9

///|
pub const Key_Market = 0x010000da

///|
pub const Key_Meeting = 0x010000db

///|
pub const Key_MenuKB = 0x010000dc

///|
pub const Key_MenuPB = 0x010000dd

///|
pub const Key_MySites = 0x010000de

///|
pub const Key_News = 0x010000df

///|
pub const Key_OfficeHome = 0x010000e0

///|
pub const Key_Option = 0x010000e1

///|
pub const Key_Paste = 0x010000e2

///|
pub const Key_Phone = 0x010000e3

///|
pub const Key_Calendar = 0x010000e4

///|
pub const Key_Reply = 0x010000e5

///|
pub const Key_Reload = 0x010000e6

///|
pub const Key_RotateWindows = 0x010000e7

///|
pub const Key_RotationPB = 0x010000e8

///|
pub const Key_RotationKB = 0x010000e9

///|
pub const Key_Save = 0x010000ea

///|
pub const Key_Send = 0x010000eb

///|
pub const Key_Spell = 0x010000ec

///|
pub const Key_SplitScreen = 0x010000ed

///|
pub const Key_Support = 0x010000ee

///|
pub const Key_TaskPane = 0x010000ef

///|
pub const Key_Terminal = 0x010000f0

///|
pub const Key_Tools = 0x010000f1

///|
pub const Key_Travel = 0x010000f2

///|
pub const Key_Video = 0x010000f3

///|
pub const Key_Word = 0x010000f4

///|
pub const Key_Xfer = 0x010000f5

///|
pub const Key_ZoomIn = 0x010000f6

///|
pub const Key_ZoomOut = 0x010000f7

///|
pub const Key_Away = 0x010000f8

///|
pub const Key_Messenger = 0x010000f9

///|
pub const Key_WebCam = 0x010000fa

///|
pub const Key_MailForward = 0x010000fb

///|
pub const Key_Pictures = 0x010000fc

///|
pub const Key_Music = 0x010000fd

///|
pub const Key_Battery = 0x010000fe

///|
pub const Key_Bluetooth = 0x010000ff

///|
pub const Key_WLAN = 0x01000100

///|
pub const Key_UWB = 0x01000101

///|
pub const Key_AudioForward = 0x01000102

///|
pub const Key_AudioRepeat = 0x01000103

///|
pub const Key_AudioRandomPlay = 0x01000104

///|
pub const Key_Subtitle = 0x01000105

///|
pub const Key_AudioCycleTrack = 0x01000106

///|
pub const Key_Time = 0x01000107

///|
pub const Key_Hibernate = 0x01000108

///|
pub const Key_View = 0x01000109

///|
pub const Key_TopMenu = 0x0100010a

///|
pub const Key_PowerDown = 0x0100010b

///|
pub const Key_Suspend = 0x0100010c

///|
pub const Key_ContrastAdjust = 0x0100010d

///|
pub const Key_TouchpadToggle = 0x01000110

///|
pub const Key_TouchpadOn = 0x01000111

///|
pub const Key_TouchpadOff = 0x01000112

///|
pub const Key_MicMute = 0x01000113

///|
pub const Key_Red = 0x01000114

///|
pub const Key_Green = 0x01000115

///|
pub const Key_Yellow = 0x01000116

///|
pub const Key_Blue = 0x01000117

///|
pub const Key_ChannelUp = 0x01000118

///|
pub const Key_ChannelDown = 0x01000119

///|
pub const Key_Guide = 0x0100011a

///|
pub const Key_Info = 0x0100011b

///|
pub const Key_Settings = 0x0100011c

///|
pub const Key_MicVolumeUp = 0x0100011d

///|
pub const Key_MicVolumeDown = 0x0100011e

///|
pub const Key_New = 0x01000120

///|
pub const Key_Open = 0x01000121

///|
pub const Key_Find = 0x01000122

///|
pub const Key_Undo = 0x01000123

///|
pub const Key_Redo = 0x01000124

///|
pub const Key_MediaLast = 0x0100ffff

///|
pub const Key_unknown = 0x01ffffff

///|
pub const Key_Call = 0x01100004

///|
pub const Key_Camera = 0x01100020

///|
pub const Key_CameraFocus = 0x01100021

///|
pub const Key_Context1 = 0x01100000

///|
pub const Key_Context2 = 0x01100001

///|
pub const Key_Context3 = 0x01100002

///|
pub const Key_Context4 = 0x01100003

///|
pub const Key_Flip = 0x01100006

///|
pub const Key_Hangup = 0x01100005

///|
pub const Key_No = 0x01010002

///|
pub const Key_Select = 0x01010000

///|
pub const Key_Yes = 0x01010001

///|
pub const Key_ToggleCallHangup = 0x01100007

///|
pub const Key_VoiceDial = 0x01100008

///|
pub const Key_LastNumberRedial = 0x01100009

///|
pub const Key_Execute = 0x01020003

///|
pub const Key_Printer = 0x01020002

///|
pub const Key_Play = 0x01020005

///|
pub const Key_Sleep = 0x01020004

///|
pub const Key_Zoom = 0x01020006

///|
pub const Key_Exit = 0x0102000a

///|
pub const Key_Cancel = 0x01020001
