///|
#borrow(self, text)
pub extern "c" fn QFontMetricsF::horizontalAdvance(
  self : QFontMetricsF,
  text : QString
) -> Double = "illusory0x0_QFontMetricsF_horizontalAdvance"

///|
#borrow(self, text)
pub extern "c" fn QFontMetricsF::boundingRect(
  self : QFontMetricsF,
  text : QString
) -> QRectF = "illusory0x0_QFontMetricsF_boundingRect"

///|
#borrow(self)
pub extern "c" fn QFontMetricsF::height(self : QFontMetricsF) -> Double = "illusory0x0_QFontMetricsF_height"

///|
#borrow(self)
pub extern "c" fn QFontMetricsF::inFontUsc4(self : QFontMetricsF) -> Bool = "illusory0x0_QFontMetricsF_inFontUsc4"
