///|
#borrow(self)
pub extern "c" fn Window::show(self : Window) = "illusory0x0_Window_show"

///|
#borrow(self)
pub extern "c" fn Window::width(self : Window) -> Int = "illusory0x0_Window_width"

///|
#borrow(self)
pub extern "c" fn Window::height(self : Window) -> Int = "illusory0x0_Window_height"

///|
#borrow(self)
pub extern "c" fn Window::devicePixelRatio(self : Window) -> Int = "illusory0x0_Window_devicePixelRatio"

///|
#borrow(self)
pub extern "c" fn Window::update(self : Window) = "illusory0x0_Window_update"
