
#borrow(self,text)
extern "c" fn QFontMetricsF::horizontalAdvance(self : QFontMetricsF, text : String) -> Double = "illusory0x0_QFontMetricsF_horizontalAdvance"

#borrow(self,text)
extern "c" fn QFontMetricsF::boundingRect(self : QFontMetricsF, text : String) -> QRectF = "illusory0x0_QFontMetricsF_boundingRect"


#borrow(self)
extern "c" fn QFontMetricsF::height(self : QFontMetricsF) -> Double = "illusory0x0_QFontMetricsF_height"

#borrow(self)
extern "c" fn QFontMetricsF::inFontUsc4(self : QFontMetricsF) -> Bool = "illusory0x0_QFontMetricsF_inFontUsc4"