///|
#borrow(self)
extern "c" fn QRectF::left(self : QRectF) -> Double = "illusory0x0_QRectF_left"

///|
#borrow(self)
extern "c" fn QRectF::top(self : QRectF) -> Double = "illusory0x0_QRectF_top"

///|
#borrow(self)
extern "c" fn QRectF::right(self : QRectF) -> Double = "illusory0x0_QRectF_right"

///|
#borrow(self)
extern "c" fn QRectF::bottom(self : QRectF) -> Double = "illusory0x0_QRectF_bottom"
